#!/usr/bin/env python3
"""Example script for ET Simul Python.

This script demonstrates the basic functionality of the ET Simul framework
"""

import numpy as np

# Import modules from the package
from et_simul.core import Eye, Camera, Light


def main():
    """Main example function demonstrating ET Simul functionality."""

    print("ET Simul Python Example")
    print("=" * 50)

    # Create an eye with a corneal radius of 7.98 mm looking out along the negative y axis
    rotation_matrix = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
    e = Eye(r_cornea=7.98e-3, fovea_displacement=False)
    e.rest_orientation = rotation_matrix

    e.position = np.array([0, 500e-3, 200e-3])

    # Create a light
    l = Light()
    l.position = np.array([200e-3, 0, 0])

    # Create a camera and point it at the eye
    c = Camera()
    # Point camera at the eye position
    c.point_at(e.position)

    # Find the 3D position of the CR generated by the light
    cr = e.find_cr(l, c)
    if cr is not None:
        print(f"CR is at ({cr[0]:.6g} {cr[1]:.6g} {cr[2]:.6g}) in space")

        # Project the CR to the camera's image plane
        cr_img, _, _ = c.project(cr)
        print(f"CR is at ({cr_img[0, 0]:.6g} {cr_img[1, 0]:.6g}) in camera image")

        # Project again, but with a Gaussian camera error of 0.5 pixels
        c.err = 0.5
        c.err_type = "gaussian"
        print(f"\nWith 0.5 pixels of Gaussian camera error:")
        cr_img_noisy, _, _ = c.project(cr)
        print(
            f"CR is at ({cr_img_noisy[0, 0]:.6g} {cr_img_noisy[1, 0]:.6g}) in camera image"
        )
    else:
        print("CR not found (outside cornea boundaries)")

    print("\nExample completed successfully!")


if __name__ == "__main__":
    main()
